version: "3.9"

services:
  mongodb:
    container_name: mongodb_service
    image: "mongo:latest"
  
  redis:
    container_name: redis_service
    image: "redis:latest"

  app:
    depends_on:
      - mongodb
      - redis
    container_name: hello-wops
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tmp:/app/logs
    links:
      - mongodb:mongo_database
      - redis:redis_database
    environment:
      - PORT=3000
      - MONGO_HOST=mongo_database
      - MONGO_PORT=27017
      - REDIS_HOST=redis_database
      - REDIS_PORT=6379
    ports:
      - "3000:3000"


    

